services:
  app:
    build: .
    container_name: finance_dashboard
    # ports:
    #   - "8501:8501"
    volumes:
      - .:/app
    networks:
      - nginx_proxy_manager_default
    
networks:
  nginx_proxy_manager_default:
    external: true