services:
  app:
    build: .
    container_name: finance_dashboard
    # ports:
    #   - "8501:8501"
    volumes:
      - .:/app
    networks:
      - nginx_proxy_manager_default
    
networks:
  nginx_proxy_manager_default:
    external: true


# git update-index --assume-unchanged docker-compose.yml
# git update-index --no-assume-unchanged docker-compose.yml